#include "TopLevelAccelerationStructureManager.h"

AccelerationStructureBuffer TopLevelAccelerationStructureManager::TopLevelAccelerationStructure{};
VulkanBuffer TopLevelAccelerationStructureManager::InstancesBuffer;