#include "TopLevelAccelerationStructureManager.h"

 AccelerationStructureBuffer TopLevelAccelerationStructureManager::TopLevelAccelerationStructure;
 VkDeviceOrHostAddressConstKHR TopLevelAccelerationStructureManager::DeviceOrHostAddressConst;
 VulkanBuffer TopLevelAccelerationStructureManager::scratchBuffer;
 VulkanBuffer TopLevelAccelerationStructureManager::InstanceBuffer;
 int TopLevelAccelerationStructureManager::AccelerationStructureInstanceCount = -1;