C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 FrameBuffer.vert -o FrameBufferVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 FrameBuffer.frag -o FrameBufferFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 MeshPicker2D.vert -o MeshPicker2DVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 MeshPicker2D.frag -o MeshPicker2DFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 MeshPicker3D.vert -o MeshPicker3DVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 MeshPicker3D.frag -o MeshPicker3DFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 Renderer2D.vert -o Renderer2DVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 Renderer2D.frag -o Renderer2DFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 Renderer3D.vert -o Renderer3DVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 Renderer3D.frag -o Renderer3DFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 BillBoardShader.vert -o BillBoardShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 BillBoardShader.frag -o BillBoardShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 PBRRenderer.vert -o PBRRendererVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 PBRRenderer.frag -o PBRRendererFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DepthShader.vert -o DepthShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DepthShader.frag -o DepthShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DepthCubeShader.vert -o DepthCubeShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DepthCubeShader.frag -o DepthCubeShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DepthDebugShader.vert -o DepthDebugShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DepthDebugShader.frag -o DepthDebugShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 ReflectionPBRShader.vert -o ReflectionPBRShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 ReflectionPBRShader.frag -o ReflectionPBRShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 GBuffer.vert -o GBufferVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 GBuffer.frag -o GBufferFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 BRDFShader.vert -o BRDFShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 BRDFShader.frag -o BRDFShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 OutlineRenderer.vert -o OutlineRendererVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 OutlineRenderer.frag -o OutlineRendererFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 SelectedObjectShader.vert -o SelectedObjectShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 SelectedObjectShader.frag -o SelectedObjectShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 CubeMap.vert -o CubeMapVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 CubeMap.frag -o CubeMapFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 IrradianceShader.vert -o IrradianceShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 IrradianceShader.frag -o IrradianceShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 PrefilterShader.vert -o PrefilterShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 PrefilterShader.frag -o PrefilterShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 EnvironmentToCubeMap.vert -o EnvironmentToCubeMapVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 EnvironmentToCubeMap.frag -o EnvironmentToCubeMapFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DeferredRenderer.vert -o DeferredRendererVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 DeferredRenderer.frag -o DeferredRendererFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 LineRenderer2D.vert -o LineRenderer2DVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 LineRenderer2D.frag -o LineRenderer2DFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 LineRenderer3D.vert -o LineRenderer3DVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 LineRenderer3D.frag -o LineRenderer3DFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 WireFrameShader.vert -o WireFrameShaderVert.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 WireFrameShader.frag -o WireFrameShaderFrag.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 closesthit.rchit -o closesthit.rchit.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 hybridclosesthit.rchit -o hybridclosesthit.rchit.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 anyhit.rahit -o anyhit.rahit.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 anyhit1.rahit -o anyhit1.rahit.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 raygen.rgen -o raygen.rgen.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 miss.rmiss -o miss.rmiss.spv
C:/VulkanSDK/1.3.204.0/Bin/glslc.exe --target-env=vulkan1.3 --target-spv=spv1.4 shadow.rmiss -o shadow.rmiss.spv
pause